Vagrant.configure("2") do |config|

    config.vm.box = "generic/debian11"

    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "forwarded_port", guest: 81, host: 8081

    config.vm.provider "virtualbox" do |vb|
       vb.name = "gitdemo.vagrant.vm"
       vb.memory = "512"
    end

    config.vm.provision "file", source: "./index.html", destination: "~/"
    config.vm.provision "file", source: "./index.php", destination: "~/"
    config.vm.provision "file", source: "./000-default.conf", destination: "~/"
    config.vm.provision "file", source: "./ports.conf", destination: "~/"

    config.vm.provision "shell", inline: <<-SHELL
       apt update -y
       apt install -y apache2 php
       cp /home/vagrant/index.* /var/www/html/
       cp /home/vagrant/000-default.conf /etc/apache2/sites-enabled/
       cp /home/vagrant/ports.conf /etc/apache2/
       systemctl reload apache2 
    SHELL
end
