jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_ADMIN}
          password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"

unclassified:
  locale:
    systemLocale: en
    ignoreAcceptLanguage: true

credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          scope:    GLOBAL
          id:          nexus-creds
          username:    ${NEXUS_USER}
          password:    ${NEXUS_USER_PASSWORD}
          description: nexus-creds

tool:
  go:
    installations:
    - name: "go-1.16"
      properties:
      - installSource:
          installers:
          - golangInstaller:
              id: "1.16"