version: '3'
services:
  jenkins:
    build:
      context: ./Jenkins
      dockerfile: Dockerfile
    ports:
      - 80:8080
    networks:
      - network
    env_file:
      - vars.env
    container_name: jenkins
  nexus:
    build:
      context: ./Nexus
      dockerfile: Dockerfile
    ports:
      - 81:8081
    networks:
      - network
    container_name: nexus
networks:
  network: