FROM golang:1.16 as builder
RUN git clone https://github.com/Fenikks/word-cloud-generator.git /tmp/wcg
RUN cd /tmp/wcg && make

FROM alpine:latest
RUN apk add gcompat
COPY --from=builder /tmp/wcg/artifacts/linux /opt/wcg
EXPOSE 8888
CMD /opt/wcg/word-cloud-generator
