Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"
    config.vm.synced_folder  ".", "/home/vagrant"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.name  = "allinone"
    end

    config.vm.define "allinone"
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "forwarded_port", guest: 81, host: 8081

    config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y ansible
        ansible-playbook -i inventory allinone.yaml
    SHELL


end