unclassified:
  locale:
    systemLocale: en
    ignoreAcceptLanguage: true

credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          scope:    GLOBAL
          id:          staging-creds
          username:    vagrant
          password:    vagrant 
          description: staging-creds
      - usernamePassword:
          scope:    GLOBAL
          id:          nexus-creds
          username:    uploader
          password:    uploader 
          description: nexus-creds
      - usernamePassword:
          scope:    GLOBAL
          id:          production-creds
          username:    vagrant
          password:    vagrant 
          description: production-creds

tool:
  go:
    installations:
    - name: "go_lang"
      properties:
      - installSource:
          installers:
          - golangInstaller:
              id: "1.16"