---
- name: Wait Jenkins
  uri:
    url: "http://localhost:8080/cli/"
    method: GET
    return_content: "yes"
    timeout: 5
    body_format: raw
    follow_redirects: "no"
    status_code: 200,403
  register: result
  until: (result.status == 403 or result.status == 200) and (result.content.find("Please wait while") == -1)
  retries: 5
  delay: 10
  changed_when: false
  check_mode: false

- name: Get Jenkins CRUMB
  uri:
    method: GET
    url: 'http://localhost:8080/crumbIssuer/api/json'
    user: "{{ jenkins_admin_user }}"
    password: "{{ jenkins_admin_password }}"
    force_basic_auth: yes
    return_content: true
  register: crumb

- name: Get Jenkins token
  uri:
    method: POST
    url: 'http://localhost:8080/user/admin/descriptorByName/jenkins.security.ApiTokenProperty/generateNewToken'
    user: "{{ jenkins_admin_user }}"
    password: "{{ jenkins_admin_password }}"
    follow_redirects: all
    headers:
      Jenkins-Crumb: '{{ crumb.json.crumb }}'
      Cookie: "{{ crumb.cookies_string }}"
    force_basic_auth: yes
    return_content: true
    body: 'newTokenName={{ crumb.json.crumb[:7] }}'
  register: token

- name: Install plugins
  jenkins_plugin:
    name: "{{ item }}"
    state: present
    timeout: 300
    with_dependencies: yes
    url_username: "{{ jenkins_admin_user }}"
    url_password: "{{ token.json.data.tokenValue }}"
  loop:
  - credentials-binding
  - credentials
  - plain-credentials
  - git-client
  - ssh-credentials
  - workflow-scm-step
  - pipeline
  - ssh
  - sshd
  - ssh-slaves
  - timestamper
  - golang
  - locale
  - ws-cleanup
  - git
  - nexus-artifact-uploader
  - configuration-as-code
  register: plugin_result
  until: plugin_result is success
  retries: 5
  delay: 10
  notify:
    - daemon-reload
    - restart jenkins

- name: Copy configuration-as-code
  copy:
    src: files/jenkins.yaml
    dest: /var/lib/jenkins/jenkins.yaml
    owner: jenkins
    group: jenkins
  notify:
    - daemon-reload
    - restart jenkins