name: Course

on: 
  # push:
  workflow_dispatch:

jobs:
  tagn:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@master
      with:
        repository: Scubik1/devops-hometasks 
    - name: bump
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Echo
      run: echo ${{ steps.bump.outputs.tag }}
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout wcg
#       uses: actions/checkout@v3.5.3
#       with:
#         repository: Scubik1/devops-hometasks 

#     - name: Login to GitHub Container Registry
#       uses: docker/login-action@v2.2.0
#       with:
#         registry: ghcr.io
#         username: ${{ github.actor }}
#         password: ${{ secrets.GITHUB_TOKEN }}

#     - name: Lower case owner
#       run: |
#         echo "ghro_lc=$(echo $GITHUB_REPOSITORY_OWNER | tr '[:upper:]' '[:lower:]')" >> ${GITHUB_ENV}

#     - name: Build and push Docker image
#       uses: docker/build-push-action@v4.1.1
#       with:
#         context: ./07-docker
#         file: ./07-docker/Dockerfile.multi
#         push: true
#         tags: ghcr.io/${{ env.ghro_lc }}/wcg:latest, ghcr.io/${{ env.ghro_lc }}/wcg:${{ github.sha }}
