name: WCG

on: 
  push:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout wcg
      uses: actions/checkout@v3.5.3
      with:
        repository: Scubik1/word-cloud-generator
    
    - name: test dir
      run: |
        pwd
        ls -lah
