name: WCG

on: 
  push:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout wcg
      uses: actions/checkout@v3.5.3
      with:
        repository: Scubik1/word-cloud-generator

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2.2.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Echo
      run: |
        echo $GITHUB_REPOSITORY_OWNER
        echo ${{ github.actor }}
        echo ${{ secrets.GITHUB_TOKEN }}
        # repository_owner=${{ github.repository_owner }}
        ghro_lc=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        echo $ghro_lc
