name: WCG

on: 
  push:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout wcg
      uses: actions/checkout@v3.5.3
      with:
        repository: Scubik1/word-cloud-generator

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2.2.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4.1.1
      with:
        context: ./07-docker
        file: $context/Dockerfile.multi
        push: true
        tags: ghcr.io/${{ env.ghro_lc }}/wcg:latest, ghcr.io/${{ env.ghro_lc }}/wcg:$GITHUB_SHA
      env:
        ghro_lc: $(echo $GITHUB_REPOSITORY_OWNER | tr '[:upper:]' '[:lower:]')